# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Laila" #LibreAI LAbs
license = "MIT"
licenselink = "https://github.com/soyva3/libreai/blob/master/LICENSE"
description = "Theme developed for the website of Libre AI"
homepage = "http://libreai.com/"
tags = ["company", "minimal"]
features = ["Bootstrap 4", "slickJS", "FontAwesome", "Responsive"]
min_version = "0.3"

[author]
  name = "To The Moon Studio"
  homepage = "http://tothemoonstudio.uy"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
